
database:
    type: postgresql:15
    disk: 1024

varnish:
    type: standard:6.0
    relationships:
        application: 'app:http'
    configuration:
        vcl: !include
            type: string
            path: config.vcl

files:
    type: network-storage:1.0
    disk: 256